# Generated by Django 2.2.3 on 2019-10-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20191002_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tienda.Categoria'),
        ),
    ]
