# Generated by Django 2.2.3 on 2019-10-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_image_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='nombre',
        ),
        migrations.AddField(
            model_name='image',
            name='imagen',
            field=models.ImageField(default=None, upload_to='ropa'),
        ),
    ]
