# Generated by Django 2.2.3 on 2019-10-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_image_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='nombre',
        ),
    ]
